version: '3.8'

services:
  backend:
    build:
      context: ./backend/
      target: dev
    command: nodemon --exec ../node_modules/.bin/ts-node ./src/index.ts
    ports:
      - '80:3000'
    user: node
    volumes:
      - ./backend/:/opt/node_app/app
      - /opt/node_app/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
    healthcheck:
      test: curl -f http://127.0.0.1:3000
    networks:
      - application_network

networks:
  application_network:
    driver: bridge
